name: massai mara park 01 compose build

on:
  workflow_dispatch

jobs:
  mmpark01_compose_build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check docker compose version
        run: docker-compose --version
    
      - name: Build with docker compose
        run: docker docker-compose build

      - name: Run with docker compose
        run: |
           docker docker-compose up -d
           sleep 30

           docker docker-compose ps
           docker docker-compose logs

      - name: run automated test #1
        run:
          curl http://localhost:8080 || exit 1

      - name: run automated test #2
        run:
          curl http://localhost:8080/images || exit 1

      - name: run automated test #3
        run:
          curl http://localhost:8080/animal || exit 1

