name: massai mara park 01 docker hub build

on:
  workflow_dispatch

jobs:
  mmpark01_compose_build:
    runs-on: ubuntu-22.04

    steps:
       - name: Checkout Code
         uses: actions/checkout@v4
    
       - name: login to docker hub
         uses: docker/login-action@v3
         with:
             username: ${{ secrets.DOCKER_USERNAME }}
             password: ${{ secrets.DOCKER_PASSWORD }}

       - name: docker operations
         run: 
            docker build -t ${{ secrets.DOCKER_USERNAME }}/massai_mara:v1 .;
            docker push ${{ secrets.DOCKER_USERNAME }}/massai_mara:v1
       - name: logout from docker hub
         if: always()
         run: docker logout
    
       - name: pull docker image
         run: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/massai_mara:v1
            docker run -d --name mmpark01 -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/massai_mara:v1
            sleep 20

            docker ps
            docker logs mmpark01