name: massai mara park 01 multiple build

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04
    name: build jar
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
    
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
            java-version: '17'
            distribution: 'temurin'
    
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: grant execute permission
        run: chmod +x gradlew

      - name: build with gradle
        run: ./gradlew clean build
      
      - name: list build/libs directory
        run: ls -al ./build/libs

  deploy:
    needs: build
    name: deploy
    runs-on: ubuntu-22.04
    
    steps:

        - name: give execute permission
          run: chmod +x build/libs/massai_mara_park-0.0.1-SNAPSHOT.jar

        - name: run springboot application
          run:
            java -jar build/libs/massai_mara_park-0.0.1-SNAPSHOT.jar & sleep 30 # stand by 30 seconds
                
  test:
    runs-on: ubuntu-22.04
    needs: deploy   
    name: app test
    steps:
        - name: run automated test #1
          run:
            curl http://localhost:8080 || exit 1

        - name: run automated test #2
          run:
            curl http://localhost:8080/images || exit 1

        - name: run automated test #3
          run:
            curl http://localhost:8080/animal || exit 1

