name: massai mara park 01 deploy ec2

on:
  workflow_dispatch

env:
  EC2_HOSTNAME: 43.203.192.114
  EC2_USERNAME: ubuntu

jobs:
  build_jar:
    runs-on: ubuntu-22.04
    name: build jar
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
    
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
            java-version: '17'
            distribution: 'temurin'
            
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: grant execute permission
        run: chmod +x gradlew
      
      - name: build with gradle
        run: ./gradlew clean build
      
      - name: list build/libs directory
        run: ls -al ./build/libs
      
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: application.jar
          path: build/libs/*SNAPSHOT.jar
  
  deploy_ec2:
    needs: build_jar
    name: JAR upload to EC2
    runs-on: ubuntu-22.04

    steps:
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
        
      - name: download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: application.jar

      - name: Setup SSH Directory
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

      - name: Make Private Key File
        run: |
          echo "${{ secrets.EC2_PRIVATEKEY }}" > ~/.ssh/ec2_key
          chmod 600 ~/.ssh/ec2_key

      - name: Upload JAR via SCP
        run: |
          scp -i ~/.ssh/ec2_key \
              -o "StrictHostKeyChecking=no" \
              -o "UserKnownHostsFile=/dev/null" \
              *SNAPSHOT.jar \
              ${{ env.EC2_USERNAME }}@${{ env.EC2_HOSTNAME }}:~/

      - name: Cleanup Private Key
        if: always()
        run: |
          rm -f ~/.ssh/ec2_key

  run_test_ec2:
    needs: deploy_ec2
    name: Run and Test on EC2
    runs-on: ubuntu-22.04
  
    steps:
      - name: Setup SSH Directory
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

      - name: Make Private Key File
        run: |
          echo "${{ secrets.EC2_PRIVATEKEY }}" > ~/.ssh/ec2_key
          chmod 600 ~/.ssh/ec2_key

      - name: Test SSH Connection to EC2  
        run: |
          echo "SSH 연결 테스트 시작 ..."
          ssh -vvv -o StrictHostKeyChecking=no \
              -o "UserKnownHostsFile=/dev/null" \
              -i ~/.ssh/ec2_key\
              ${{ env.EC2_USERNAME }}@${{ env.EC2_HOSTNAME }} '
                echo "JAR 파일 실행 ..."
                java -jar ./massai_mara_park-0.0.1-SNAPSHOT.jar # stand by 30 seconds
              '
    
      - name: Cleanup Private Key
        if: always()
        run: |
          rm -f ~/.ssh/ec2_key
      